### ISSUE TITLE
Why [DEPRECATED]?

### ISSUE THREAD

**Issue by soulcreate** [chilloutdevelopment/ChillDevSpintax#5]
Hello! please say why this library deprecated? What is mean?

**Comment by rafalwrzeszcz** [comment]
Well, maybe it's not the best description - it works how it used to do, just no longer maintained (no time for that from my side). I don't guarantee that it has no outdated dependencies etc. Apart from that everything stays useful. If you are interested, feel free to contribute.

**Comment by rafalwrzeszcz** [comment]
I'll change description to not scare people so much,
